
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_BUTTONSWITCH_GPIO_DEVICE_ID,
		XPAR_AXI_BUTTONSWITCH_GPIO_BASEADDR,
		XPAR_AXI_BUTTONSWITCH_GPIO_INTERRUPT_PRESENT,
		XPAR_AXI_BUTTONSWITCH_GPIO_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_0_DEVICE_ID,
		XPAR_AXI_GPIO_0_BASEADDR,
		XPAR_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_XADC_DATA_READ_DEVICE_ID,
		XPAR_AXI_GPIO_XADC_DATA_READ_BASEADDR,
		XPAR_AXI_GPIO_XADC_DATA_READ_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_XADC_DATA_READ_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_XADC_DATA_WRITE_DEVICE_ID,
		XPAR_AXI_GPIO_XADC_DATA_WRITE_BASEADDR,
		XPAR_AXI_GPIO_XADC_DATA_WRITE_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_XADC_DATA_WRITE_IS_DUAL
	}
};


