# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/nexysA7fpga.xdc

# Block Designs: bd/embsys/embsys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys || ORIG_REF_NAME==embsys} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_0 || ORIG_REF_NAME==embsys_microblaze_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_nexys4io_0_0/embsys_nexys4io_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_nexys4io_0_0 || ORIG_REF_NAME==embsys_nexys4io_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_0_0 || ORIG_REF_NAME==embsys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_timer_0_0 || ORIG_REF_NAME==embsys_axi_timer_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_fit_timer_0_0/embsys_fit_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_fit_timer_0_0 || ORIG_REF_NAME==embsys_fit_timer_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_uartlite_0_0 || ORIG_REF_NAME==embsys_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_dlmb_v10_0 || ORIG_REF_NAME==embsys_dlmb_v10_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_ilmb_v10_0 || ORIG_REF_NAME==embsys_ilmb_v10_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_bram_if_cntlr_0/embsys_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==embsys_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_bram_if_cntlr_0/embsys_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==embsys_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_lmb_bram_0/embsys_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_lmb_bram_0 || ORIG_REF_NAME==embsys_lmb_bram_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xbar_0/embsys_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_xbar_0 || ORIG_REF_NAME==embsys_xbar_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_periph_0/embsys_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_periph_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_intc_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_xlconcat_0/embsys_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_xlconcat_0 || ORIG_REF_NAME==embsys_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_mdm_1_0 || ORIG_REF_NAME==embsys_mdm_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_clk_wiz_1_0 || ORIG_REF_NAME==embsys_clk_wiz_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==embsys_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/embsys_PmodOLEDrgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_PmodOLEDrgb_0_0 || ORIG_REF_NAME==embsys_PmodOLEDrgb_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_timebase_wdt_0_0/embsys_axi_timebase_wdt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_timebase_wdt_0_0 || ORIG_REF_NAME==embsys_axi_timebase_wdt_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_0_4/embsys_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_0_4 || ORIG_REF_NAME==embsys_axi_gpio_0_4} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xlconcat_0_1/embsys_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_xlconcat_0_1 || ORIG_REF_NAME==embsys_xlconcat_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xlconstant_0_1/embsys_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_xlconstant_0_1 || ORIG_REF_NAME==embsys_xlconstant_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xadc_wiz_0_0/embsys_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_xadc_wiz_0_0 || ORIG_REF_NAME==embsys_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_PWM_0_0/embsys_PWM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_PWM_0_0 || ORIG_REF_NAME==embsys_PWM_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_PmodENC544_0_0/embsys_PmodENC544_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_PmodENC544_0_0 || ORIG_REF_NAME==embsys_PmodENC544_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_1_0 || ORIG_REF_NAME==embsys_axi_gpio_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xlconstant_0_2/embsys_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_xlconstant_0_2 || ORIG_REF_NAME==embsys_xlconstant_0_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_XADC_Data_Out_0/embsys_axi_gpio_XADC_Data_Out_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_XADC_Data_Out_0 || ORIG_REF_NAME==embsys_axi_gpio_XADC_Data_Out_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xlconstant_1_0/embsys_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_xlconstant_1_0 || ORIG_REF_NAME==embsys_xlconstant_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_tier2_xbar_0_0/embsys_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_tier2_xbar_0_0 || ORIG_REF_NAME==embsys_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_tier2_xbar_1_0/embsys_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_tier2_xbar_1_0 || ORIG_REF_NAME==embsys_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_tier2_xbar_2_0/embsys_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_tier2_xbar_2_0 || ORIG_REF_NAME==embsys_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_0/embsys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_auto_pc_0 || ORIG_REF_NAME==embsys_auto_pc_0} -quiet] -quiet

# XDC: d:/PSU_Work_and_Textbooks/ECE544/ECE544_ProjFinal/ECE-544-final-project/Photo_Motor_Vivado/Photo_Motor_Vivado.gen/sources_1/bd/embsys/embsys_ooc.xdc
