# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/PSU_Work_and_Textbooks/ECE544/ECE544_ProjFinal/ECE-544-final-project/Photo_ADC_Motor/Photo_ADC_Motor.srcs/sources_1/bd/embsys/ip/embsys_tier2_xbar_0_0/embsys_tier2_xbar_0_0.xci
# IP: The module: 'embsys_tier2_xbar_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PSU_Work_and_Textbooks/ECE544/ECE544_ProjFinal/ECE-544-final-project/Photo_ADC_Motor/Photo_ADC_Motor.gen/sources_1/bd/embsys/ip/embsys_tier2_xbar_0_0/embsys_tier2_xbar_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_tier2_xbar_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/PSU_Work_and_Textbooks/ECE544/ECE544_ProjFinal/ECE-544-final-project/Photo_ADC_Motor/Photo_ADC_Motor.srcs/sources_1/bd/embsys/ip/embsys_tier2_xbar_0_0/embsys_tier2_xbar_0_0.xci
# IP: The module: 'embsys_tier2_xbar_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PSU_Work_and_Textbooks/ECE544/ECE544_ProjFinal/ECE-544-final-project/Photo_ADC_Motor/Photo_ADC_Motor.gen/sources_1/bd/embsys/ip/embsys_tier2_xbar_0_0/embsys_tier2_xbar_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_tier2_xbar_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
